version: '3.7'

services:
    hadoop:
        container_name: hadoop
        image: docker.pkg.github.com/minhthong582000/my-data-stack/hadoop:latest
        # build:
        #     context: ./hadoop
        restart: always
        ports:
            - "8088:8088"
            - "50070:50070"
            - "50075:50075"
        volumes:
            - ./sample:/var/log/sample
            - datanode:/tmp/hadoop-root
        networks:
            hadoop:
                ipv4_address: 172.28.1.10

    web:
        container_name: web
        image: nginx
        volumes:
            - ./sample:/var/log/nginx
        ports:
            - "80:80"
        networks:
            - web

# Volumes
volumes: 
    datanode:

# Network
networks:
    hadoop:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16
    web:
